# List vs Tuple

In [1]:
x = [5,10,0]
x

[5, 10, 0]

In [2]:
type(x)

list

In [3]:
y = (5,10,0)
y

(5, 10, 0)

In [4]:
type(y)

tuple

### Tuple are immutable

In [5]:
x[2] = -1
x

[5, 10, -1]

In [6]:
y[2]=-1

TypeError: 'tuple' object does not support item assignment

### Tuple with one entry

In [7]:
x = [5]
x

[5]

In [8]:
tpl = (5)
tpl

5

In [9]:
type(tpl)

int

In [10]:
tpl = (5,)
tpl

(5,)

In [11]:
type(tpl)

tuple

# NUMPY NDARRAYS

https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html

In [12]:
import numpy as np

### Construct a vector with 3 entries

In [13]:
x = np.array( [5.3 , 2.1 , -3.1 ] )
print(x)

[ 5.3  2.1 -3.1]


In [14]:
type(x)

numpy.ndarray

### Add two ndarrays

In [15]:
x = np.array([1,2,3])
y = np.array([1,1,1])
z = x+y
z

array([2, 3, 4])

### Add two lists

In [16]:
x = [1,2,3]
y = [1,1,1]
z = x+y
z

[1, 2, 3, 1, 1, 1]

### Construct a  2 x 2 matrix

In [17]:
A = np.array( [ [5.3,2.1] , [0.2,2.1] ] )
print(A)

[[5.3 2.1]
 [0.2 2.1]]


### Construct a 10 x 2 matrix filled with zeros

In [18]:
A = np.zeros( (10,2) )
A

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

### The argument of the zeros() function is a tuple that provide the shape of the matrix

In [19]:
s = (10,2)
type(s)

tuple

In [20]:

A = np.zeros(s)
A

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

### Vector filled with zeros

In [21]:
s = (5,)
s

(5,)

In [22]:
v = np.zeros(s)
v

array([0., 0., 0., 0., 0.])

In [23]:
# but this also works
w = np.zeros(5)
w

array([0., 0., 0., 0., 0.])

### 3-dimensional matrix

In [24]:
A = np.zeros( (5,2,2) )
A

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

### Matrix filled with ones 

In [25]:
A = np.ones( (2,10) )
A

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### Matrix filled with sevens

In [26]:
s = (2,10)
A = np.full(s,7.5)
A

array([[7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5],
       [7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5, 7.5]])

### Identity matrix

In [27]:
Id = np.eye(4)
Id

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random matrix

In [28]:
A = np.random.random( (10,3) )
A

array([[0.76578733, 0.81118188, 0.50614127],
       [0.90536378, 0.43830595, 0.9992383 ],
       [0.73289996, 0.67328764, 0.45860037],
       [0.42411021, 0.23232108, 0.04702184],
       [0.82175248, 0.36860751, 0.16992777],
       [0.13844756, 0.94207959, 0.38952879],
       [0.43871508, 0.32700143, 0.66090065],
       [0.74819179, 0.93392071, 0.56559405],
       [0.26501573, 0.35760319, 0.74133933],
       [0.66591298, 0.36480474, 0.21736153]])

### Range vector

In [29]:
v = np.arange(5,11)
v

array([ 5,  6,  7,  8,  9, 10])

In [30]:
v = np.arange(0,11,2)
v

array([ 0,  2,  4,  6,  8, 10])

In [31]:
v = np.arange(0,10,0.1)
v

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

### The shape attribute

In [32]:
A = np.zeros((2,8))
print(A)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [33]:
A.shape  

(2, 8)

In [34]:
type(A.shape)

tuple

In [35]:
v = np.arange(5,11)
v

array([ 5,  6,  7,  8,  9, 10])

In [36]:
v.shape

(6,)

### The ndim attribute
* A vector is a 1-dimensional array
* A matrix is a 2-dimensional array
* You can generalize and have n-dimensional array

In [37]:
v = np.array([5,10,20])
v

array([ 5, 10, 20])

In [38]:
v.ndim

1

In [39]:
v.shape

(3,)

In [40]:
A = np.array([[5,10,20], [1,1,1], [1,2,2], [3,3,1] ])
A

array([[ 5, 10, 20],
       [ 1,  1,  1],
       [ 1,  2,  2],
       [ 3,  3,  1]])

In [41]:
A.ndim

2

In [42]:
A.shape

(4, 3)

In [43]:
a = np.zeros((2,3,3))
a

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [44]:
a.ndim

3

In [45]:
a.shape

(2, 3, 3)

### The data-type attribute

In [46]:
v = np.array([1,2,3])
v

array([1, 2, 3])

In [47]:
v.dtype

dtype('int64')

In [48]:
w = np.array([1.0,2.0,3.0])
w

array([1., 2., 3.])

In [49]:
w.dtype

dtype('float64')

In [50]:
A = np.random.random( (3,3) )
A

array([[0.27286103, 0.50160067, 0.83499024],
       [0.12369843, 0.10426578, 0.42160332],
       [0.46170481, 0.33537053, 0.64041263]])

In [51]:
A.dtype

dtype('float64')

In [52]:
# compare with:
type(A)

numpy.ndarray

### The astype() method

In [53]:
A = np.zeros((2,2))
A

array([[0., 0.],
       [0., 0.]])

In [54]:
A.dtype

dtype('float64')

In [55]:
A = A.astype(int)
A

array([[0, 0],
       [0, 0]])

In [56]:
A.dtype

dtype('int64')

In [57]:
v = np.arange(0,5)
v

array([0, 1, 2, 3, 4])

In [58]:
v = v.astype(float)

In [59]:
v

array([0., 1., 2., 3., 4.])

### min(), max(), and mean() methods

In [60]:
v = np.array([90.,100.,94.,96.])
v

array([ 90., 100.,  94.,  96.])

In [61]:
v.min()

90.0

In [62]:
v.max()

100.0

In [63]:
v.mean()

95.0

In [64]:
v.std()

3.605551275463989

### Adding and multiplying arrays

In [65]:
A = np.array([[1,2],[3,4]])
B = np.array([[10,5],[30,50]])

C = 2*B
D = A+B

print('\n A=')
print(A)
print('\n B=')
print(B)

print('\n 2B =')
print(C)
print('\n A+B =')
print(A+B)


 A=
[[1 2]
 [3 4]]

 B=
[[10  5]
 [30 50]]

 2B =
[[ 20  10]
 [ 60 100]]

 A+B =
[[11  7]
 [33 54]]
