# NUMPY ARRAY

In [2]:
import numpy as np

### Make the matrices A and B below. Add them together to obtain a matrix C. Print these three matrices.
$$
A =\begin{bmatrix}
1 & 2 \\ 3 & 4
\end{bmatrix}  
\qquad 
B =\begin{bmatrix}
10 & 20 \\ 30 & 40
\end{bmatrix}  \qquad C=A+B =?
$$

In [3]:
A = np.array( [[1,2],[3,4]])
B = np.array( [[10,20],[30,40]])
C = A+B
C

array([[11, 22],
       [33, 44]])

### Print the shape and data-type of the matrix A. 

In [4]:
print(A.shape)
print(A.dtype)

(2, 2)
int64


### Convert the matrix A to be made of floats.  Then print the type to check it was indeed converted.

In [6]:
A = A.astype(float)
print(A)
print(A.dtype)


[[1. 2.]
 [3. 4.]]
float64


### Make a random 5 x 2 x 3 Tensor. The command is torch.rand.  Then do the following:   1) Print the tensor,  2) Print its type, 3) Print its dimension,  4) Print its size, 5) Print the size of its middle dimension.

In [8]:
A = np.random.random_sample((5,2,3))
A



array([[[0.65867869, 0.33571555, 0.74220958],
        [0.29781445, 0.82537124, 0.33892001]],

       [[0.8059862 , 0.18975651, 0.37683197],
        [0.22865242, 0.54497609, 0.96160271]],

       [[0.02534813, 0.31695633, 0.63723645],
        [0.871166  , 0.27685917, 0.60256562]],

       [[0.28251567, 0.01822773, 0.97008166],
        [0.33718514, 0.86264036, 0.34057775]],

       [[0.5002182 , 0.60607138, 0.58164497],
        [0.12433864, 0.587254  , 0.41403784]]])

In [9]:
print(A.shape)
print(A.dtype)

(5, 2, 3)
float64
