### Problem 1: Compute the following by hand (the symbol $\otimes$ means component wise multiplication)
$$
\begin{bmatrix}
1&2&3 \\
2&2&2
\end{bmatrix} \otimes
\begin{bmatrix}
1&1&1 \\
2&2&2
\end{bmatrix} = 
\begin{bmatrix}
1&2&3 \\
4&4&4
\end{bmatrix}
$$



$$
\begin{bmatrix}
1&2&3 \\
1&2&2
\end{bmatrix}
\begin{bmatrix}
1&2 \\
1&2 \\
1&2 
\end{bmatrix}
=
\begin{bmatrix}
6&12 \\
5&10
\end{bmatrix}
$$



$$
\begin{bmatrix}
1&2&3 \\
1&2&2
\end{bmatrix} 
\begin{bmatrix}
1 \\1 \\1
\end{bmatrix} = 
\begin{bmatrix}
6 \\5
\end{bmatrix}
$$



$$
\begin{bmatrix}
1\\2\\3
\end{bmatrix} 
\cdot
\begin{bmatrix}
2 \\1 \\2
\end{bmatrix} = 10
$$

$$
\begin{bmatrix}
1\\2\\3
\end{bmatrix} 
\otimes
\begin{bmatrix}
2 \\1 \\2
\end{bmatrix} = 
\begin{bmatrix}
2 \\2 \\6
\end{bmatrix}
$$





### Problem 2: Compute the above with numpy

In [2]:
import numpy as np

In [3]:
A = np.array([[1,2,3],[2,2,2]])
B = np.array([[1,1,1],[2,2,2]])
A*B

array([[1, 2, 3],
       [4, 4, 4]])

In [6]:
A = np.array([[1,2,3],[1,2,2]])
B = np.array([[1,2],[1,2],[1,2]])
np.dot(A,B)

array([[ 6, 12],
       [ 5, 10]])

In [7]:
v = np.array([1,1,1])
np.dot(A,v)

array([6, 5])

In [9]:
v = np.array([1,2,3])
w = np.array([2,1,2])
print(np.dot(v,w))
print(v*w)

10
[2 2 6]


### Problem 3: Solve the following system by hand:
\begin{align}
&x + 2y = 5 \\
&3x + 4y = 11
\end{align}

Doing Gaussian elimination the system becomes

\begin{align}
&x + 2y = 5 \\
&0x + -2y = -4
\end{align}

Then backsubstitution gives $y = 2$ and $x=1$

### Problem 4: solve the above system with the linalg module

In [10]:
from scipy import linalg

In [13]:
A = np.array([[1,2],[3,4]])
b = np.array([5,11])
x = linalg.solve(A,b)
x

array([1., 2.])